# Generated by Django 5.2 on 2025-04-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_medicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="purpose",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
