# Generated by Django 5.2 on 2025-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_medicine_purpose_alter_medicine_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="shelf",
            field=models.CharField(max_length=10),
        ),
    ]
