# Generated by Django 5.2 on 2025-04-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_alter_medicine_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="price",
            field=models.FloatField(default=10, max_length=100),
        ),
    ]
