# Generated by Django 5.2 on 2025-04-25 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="point",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="sale",
            name="sale_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price_at_sale", models.FloatField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.medicine",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="customer.sale",
                    ),
                ),
            ],
        ),
    ]
