# Generated by Django 5.2 on 2025-04-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_alter_customer_point_alter_sale_sale_date_saleitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
    ]
